-- Cashier accountability and duplicate-sale protection.
-- Run after supabase-orders-payments-migration.sql.

alter table public.orders
  add column if not exists cash_received numeric(12, 2),
  add column if not exists change_due numeric(12, 2),
  add column if not exists completed_by uuid references auth.users(id),
  add column if not exists completed_at timestamptz,
  add column if not exists idempotency_key text;

create unique index if not exists orders_idempotency_key_idx
  on public.orders(idempotency_key)
  where idempotency_key is not null;

create table if not exists public.order_audit_events (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete restrict,
  actor_id uuid references auth.users(id),
  actor_role text not null,
  event_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists order_audit_events_order_id_idx
  on public.order_audit_events(order_id, created_at desc);

alter table public.order_audit_events enable row level security;
revoke all on public.order_audit_events from anon, authenticated;
revoke all on function public.finalize_order_inventory(bigint, text) from public, anon, authenticated;

notify pgrst, 'reload schema';