-- Run in Supabase Dashboard > SQL Editor.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  shift_id uuid,
  cashier_id uuid references auth.users(id),
  customer_name text,
  customer_phone text,
  total_amount numeric(12, 2) not null,
  payment_method text not null default 'Cash',
  status text not null default 'pending',
  created_at timestamptz default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id text,
  product_name text not null,
  unit_price numeric(12, 2) not null,
  quantity integer not null,
  subtotal numeric(12, 2) not null
);

-- Keep existing installations compatible with the customer checkout flow.
alter table public.orders
  add column if not exists shift_id uuid,
  add column if not exists cashier_id uuid,
  add column if not exists customer_id uuid references auth.users(id) on delete set null,
  add column if not exists customer_name text,
  add column if not exists customer_phone text,
  add column if not exists total_amount numeric(12, 2),
  add column if not exists payment_method text default 'Cash',
  add column if not exists status text default 'pending',
  add column if not exists created_at timestamptz default now();

alter table public.orders
  add column if not exists inventory_status text not null default 'legacy',
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists last_status_changed_by uuid;

alter table public.order_items
  add column if not exists order_id bigint,
  add column if not exists product_id text,
  add column if not exists product_name text,
  add column if not exists unit_price numeric(12, 2),
  add column if not exists quantity integer,
  add column if not exists subtotal numeric(12, 2);

create or replace function public.set_order_audit()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if auth.uid() is not null then
    new.last_status_changed_by = auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_order_audit on public.orders;
create trigger trg_order_audit
before insert or update on public.orders
for each row
when (pg_trigger_depth() = 0)
execute procedure public.set_order_audit();

-- Inventory reservations prevent concurrent storefront/POS sales from
-- overselling stock while a payment is still pending.
alter table public.products
  add column if not exists stock_reserved integer not null default 0;

update public.products
set stock_reserved = 0
where stock_reserved is null;

alter table public.products
  drop constraint if exists products_stock_reserved_nonnegative;

alter table public.products
  add constraint products_stock_reserved_nonnegative
  check (stock_reserved >= 0);

drop function if exists public.create_reserved_order(jsonb, uuid, text, text, text, bigint, uuid, boolean);

create or replace function public.create_reserved_order(
  p_items jsonb,
  p_customer_id uuid default null,
  p_customer_name text default null,
  p_customer_phone text default null,
  p_payment_method text default 'Pesapal',
  p_shift_id uuid default null,
  p_cashier_id uuid default null,
  p_confirmed boolean default false
)
returns table (id bigint, total_amount numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  requested record;
  product_row record;
  created_order_id bigint;
  calculated_total numeric(12, 2) := 0;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Cart items are required.' using errcode = '22023';
  end if;

  -- Aggregate duplicate product IDs and lock rows in ID order to avoid
  -- overselling and reduce deadlock risk when carts overlap.
  for requested in
    select value->>'productId' as product_id,
           sum((value->>'quantity')::integer)::integer as quantity
    from jsonb_array_elements(p_items) as item(value)
    group by value->>'productId'
    order by (value->>'productId')::bigint
  loop
    if requested.quantity < 1 or requested.quantity > 100 then
      raise exception 'Invalid product quantity.' using errcode = '22023';
    end if;

    select p.id, p.name, p.price, p.stock_quantity, p.stock_reserved
    into product_row
    from public.products p
    where p.id = requested.product_id::bigint
    for update;

    if not found then
      raise exception 'Product % is unavailable.', requested.product_id using errcode = 'P0001';
    end if;

    if coalesce(product_row.stock_quantity, 0) - coalesce(product_row.stock_reserved, 0) < requested.quantity then
      raise exception 'Insufficient stock for product %.', requested.product_id using errcode = 'P0001';
    end if;

    calculated_total := calculated_total + (product_row.price * requested.quantity);
    update public.products
    set stock_reserved = coalesce(stock_reserved, 0) + requested.quantity
    where public.products.id = product_row.id;
  end loop;

  insert into public.orders (
    customer_id, shift_id, cashier_id, customer_name, customer_phone,
    total_amount, payment_method, status
  ) values (
    p_customer_id, p_shift_id, p_cashier_id, nullif(trim(p_customer_name), ''),
    nullif(trim(p_customer_phone), ''), calculated_total, p_payment_method,
    case when p_confirmed then 'completed' else 'pending' end
  ) returning public.orders.id into created_order_id;

  update public.orders
  set inventory_status = case when p_confirmed then 'finalized' else 'reserved' end
  where public.orders.id = created_order_id;

  for requested in
    select value->>'productId' as product_id,
           sum((value->>'quantity')::integer)::integer as quantity
    from jsonb_array_elements(p_items) as item(value)
    group by value->>'productId'
  loop
    select p.name, p.price
    into product_row
    from public.products p
    where p.id = requested.product_id::bigint;

    insert into public.order_items (
      order_id, product_id, product_name, unit_price, quantity, subtotal
    ) values (
      created_order_id, requested.product_id::bigint, product_row.name, product_row.price,
      requested.quantity, product_row.price * requested.quantity
    );
  end loop;

  if p_confirmed then
    for requested in
      select value->>'productId' as product_id,
             sum((value->>'quantity')::integer)::integer as quantity
      from jsonb_array_elements(p_items) as item(value)
      group by value->>'productId'
    loop
      update public.products
      set stock_quantity = coalesce(stock_quantity, 0) - requested.quantity,
          stock_reserved = stock_reserved - requested.quantity
      where public.products.id = requested.product_id::bigint;
    end loop;
  end if;

  return query select created_order_id, calculated_total;
end;
$$;

create or replace function public.finalize_order_inventory(
  p_order_id bigint,
  p_new_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_order record;
  line record;
begin
  select id, status, inventory_status into current_order
  from public.orders
  where public.orders.id = p_order_id
  for update;

  if not found or current_order.status <> 'pending' or current_order.inventory_status <> 'reserved' then
    return;
  end if;

  for line in
    select product_id, quantity
    from public.order_items
    where order_id = p_order_id
  loop
    if p_new_status = 'completed' then
      update public.products
      set stock_quantity = coalesce(stock_quantity, 0) - line.quantity,
          stock_reserved = stock_reserved - line.quantity
      where public.products.id = line.product_id::bigint;
    elsif p_new_status in ('failed', 'cancelled', 'expired') then
      update public.products
      set stock_reserved = stock_reserved - line.quantity
      where public.products.id = line.product_id::bigint;
    else
      raise exception 'Unsupported inventory status %.', p_new_status using errcode = '22023';
    end if;
  end loop;

  update public.orders
  set status = p_new_status,
      inventory_status = case when p_new_status = 'completed' then 'finalized' else 'released' end,
      updated_at = now()
  where public.orders.id = p_order_id;
end;
$$;

create or replace function public.expire_stale_order_reservations(
  p_timeout interval default interval '30 minutes'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  pending_order record;
  expired_count integer := 0;
begin
  for pending_order in
    select id
    from public.orders
    where status = 'pending'
      and inventory_status = 'reserved'
      and created_at < now() - p_timeout
    for update skip locked
  loop
    perform public.finalize_order_inventory(pending_order.id, 'expired');
    expired_count := expired_count + 1;
  end loop;
  return expired_count;
end;
$$;

-- These functions are backend-only. Browser clients must not call them
-- directly to reserve, finalize, or release inventory.
revoke all on function public.create_reserved_order(jsonb, uuid, text, text, text, uuid, uuid, boolean) from public, anon, authenticated;
revoke all on function public.finalize_order_inventory(bigint, text) from public, anon, authenticated;
revoke all on function public.expire_stale_order_reservations(interval) from public, anon, authenticated;
grant execute on function public.create_reserved_order(jsonb, uuid, text, text, text, uuid, uuid, boolean) to service_role;
grant execute on function public.finalize_order_inventory(bigint, text) to service_role;
grant execute on function public.expire_stale_order_reservations(interval) to service_role;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists customer_checkout_insert_orders on public.orders;
drop policy if exists customer_checkout_insert_order_items on public.order_items;
drop policy if exists customer_checkout_insert_orders_anon on public.orders;
drop policy if exists customer_checkout_insert_orders_authenticated on public.orders;
drop policy if exists customer_checkout_insert_order_items_anon on public.order_items;
drop policy if exists customer_checkout_insert_order_items_authenticated on public.order_items;

create table if not exists public.payment_transactions (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  provider text not null check (provider in ('mtn', 'airtel')),
  customer_phone text not null,
  amount numeric(12, 2) not null,
  status text not null default 'pending',
  provider_transaction_id text,
  provider_reference text,
  failure_reason text,
  created_at timestamptz default now()
);

alter table public.payment_transactions
  add column if not exists provider_reference text;

alter table public.orders
  add column if not exists pesapal_tracking_id text,
  add column if not exists pesapal_merchant_reference text,
  add column if not exists pesapal_redirect_url text,
  add column if not exists updated_at timestamptz default now();

create unique index if not exists orders_pesapal_tracking_id_idx
  on public.orders(pesapal_tracking_id)
  where pesapal_tracking_id is not null;

create index if not exists order_items_order_id_idx
  on public.order_items(order_id);

create index if not exists orders_customer_id_idx
  on public.orders(customer_id);

create index if not exists payment_transactions_order_id_idx
  on public.payment_transactions(order_id);

notify pgrst, 'reload schema';
