-- Run in Supabase Dashboard > SQL Editor.

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin';
$$;

create table if not exists public.customer_requests (
  id bigint generated by default as identity primary key,
  customer_name text not null check (length(trim(customer_name)) > 0),
  phone text not null check (length(trim(phone)) > 0),
  item_name text not null check (length(trim(item_name)) > 0),
  notes text,
  source text not null default 'online' check (source in ('online', 'manual')),
  status text not null default 'pending' check (status in ('pending', 'assigned', 'completed', 'cancelled')),
  assigned_cashier text not null default 'Unassigned',
  received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid
);

create index if not exists customer_requests_created_at_idx
  on public.customer_requests(created_at desc);

create or replace function public.set_customer_request_audit()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  if auth.uid() is not null then
    new.updated_by = auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_customer_request_audit on public.customer_requests;
create trigger trg_customer_request_audit
before insert or update on public.customer_requests
for each row
execute procedure public.set_customer_request_audit();

alter table public.customer_requests enable row level security;

drop policy if exists customer_requests_insert on public.customer_requests;
create policy customer_requests_insert
  on public.customer_requests for insert
  to anon, authenticated
  with check (
    length(trim(customer_name)) > 0 and
    length(trim(phone)) > 0 and
    length(trim(item_name)) > 0 and
    source in ('online', 'manual') and
    status in ('pending', 'assigned', 'completed', 'cancelled')
  );

drop policy if exists customer_requests_admin_select on public.customer_requests;
create policy customer_requests_admin_select
  on public.customer_requests for select
  to authenticated
  using (public.is_admin());

drop policy if exists customer_requests_admin_update on public.customer_requests;
create policy customer_requests_admin_update
  on public.customer_requests for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists customer_requests_admin_delete on public.customer_requests;
create policy customer_requests_admin_delete
  on public.customer_requests for delete
  to authenticated
  using (public.is_admin());

notify pgrst, 'reload schema';